users:
 - user01
 - user02
 - user03
 - user04
 - user05
 - user06
 - user07
 - user08
 - user09
 - user10
grafana:
  image:
    repository: registry.puzzle.ch/docker.io/grafana
    tag: 8.3.1
  rbac:
    create: true
    pspEnabled: false
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx-public
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
      - grafana-ops.training.acend.ch
    tls:
      - secretName: grafana-openshift-4-ops-training-monitoring
        hosts:
         - grafana-ops.training.acend.ch
  persistence:
    enabled: false
    size: "1Gi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://acend-ocp-uptime-monitoring-prometheus-server
        access: proxy
        isDefault: true
  sidecar:
    dashboards:
      enabled: true
      labelValue: dashboard
prometheus-blackbox-exporter:
  image:
    repository: quay.io/prometheus/blackbox-exporter
    tag: v0.19.0
  pspEnabled: false
  config:
    modules:
      http:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.0", "HTTP/1.1", "HTTP/2.0"]
          valid_status_codes:
            - 200
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
prometheus:
  configmapReload:
    prometheus:
      image:
        repository: quay.io/astronomer/ap-configmap-reloader
        tag: 0.5.0-1
    alertmanager:
      image:
        repository: quay.io/astronomer/ap-configmap-reloader
        tag: 0.5.0-1
  image:
    repository: quay.io/prometheus/prometheus
  rbac:
    create: false
  alertmanager:
    image:
      repository: quay.io/prometheus/alertmanager
    enabled: true
    useClusterRole: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: true